# Generated by Django 2.2.16 on 2020-09-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpdapi', '0002_auto_20150118_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=512),
        ),
    ]
